[tox]
envlist = py{310,311,312,313}-test
requires = pip >= 18.0
isolated_build = true

[testenv]
changedir =
    test: .tmp/{envname}
deps =
    visual: playwright==1.41.2
    visual: pytest-playwright==0.5.2
    visual: pytest-mpl>=0.19.0
    visual: solara[pytest]>=1.44.1
    visual: starlette<1.0
extras =
    test: test
commands =
    test: pytest --pyargs bqplot_linlog -p no:warnings {posargs}
    visual: playwright install chromium
    visual: pytest tests/ui --mpl -m mpl_image_compare --mpl-generate-summary=html --mpl-results-path={toxinidir}/results {posargs}
