[tox]
envlist = py{310,311,312,313}-{test,visual}-{bqplot012,bqplot013}
requires = pip >= 18.0
isolated_build = true

[testenv]
changedir =
    test: .tmp/{envname}
setenv =
    bqplot012: BQPLOT_BASELINE = bqplot012
    bqplot013: BQPLOT_BASELINE = bqplot013
deps =
    visual: playwright==1.41.2
    visual: pytest-playwright==0.5.2
    visual: pytest-mpl>=0.19.0
    visual: starlette<1.0
    visual-bqplot012: solara[pytest]>=1.44.1
    visual-bqplot012: jupyterlab<4
    visual-bqplot013: pytest-ipywidgets==1.57.3
    visual-bqplot013: solara>=1.44.1
    visual-bqplot013: notebook<7
    visual-bqplot013: jupyterlab<4
    bqplot012: bqplot>=0.12,<0.13
    bqplot013: bqplot>=0.13,<0.14
extras =
    test: test
commands =
    test: pip freeze
    test: pytest --pyargs bqplot_linlog -p no:warnings {posargs}
    visual: playwright install chromium
    visual: pytest tests/ui --mpl -m mpl_image_compare --mpl-baseline-path={toxinidir}/tests/ui/baseline/{env:BQPLOT_BASELINE} --mpl-generate-summary=html --mpl-results-path={toxinidir}/results {posargs}
